### ISSUE TITLE
API todo get is currently dummy and doesn't get the correct todo

### ISSUE THREAD

**Issue by daulex** [daulex/ddapi#1]
Currently /todo/get gets the same one, hardcoded, test todo list for everyone.

Need to rework/expand the API to:
- [x] /wp-json/ddapi/todo/get — should get TODAY's TODO
- [x] /wp-json/ddapi/todo/get/<id> — should get specific todo, by todo id
- [x] /wp-json/ddapi/todo/get/000 — should get ALL todos, belonging to <current_user>

**Comment by daulex** [comment]
now implemented and working.
